// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: 1.8_t&h_demo

#ifndef _1_8_T&H_DEMO_UI_H
#define _1_8_T&H_DEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_478665424);    // assets/天气 (3).png
LV_IMG_DECLARE(ui_img_t_png);    // assets/T.png
LV_IMG_DECLARE(ui_img_h_png);    // assets/H.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
